"""
PathPilot AI — Learning Roadmap

Frontend/UI rendering for the roadmap generated by the
existing IntelligenceEngine.

No backend logic is modified.
"""

import html
import streamlit as st


# ==============================================================
# STATUS CONFIGURATION
# ==============================================================

STATUS_OPTIONS = [
    "Not Started",
    "In Progress",
    "Completed",
]


STATUS_CONFIG = {

    "Not Started": {
        "label": "○",
        "class": "roadmap-not-started",
    },

    "In Progress": {
        "label": "◐",
        "class": "roadmap-in-progress",
    },

    "Completed": {
        "label": "✓",
        "class": "roadmap-completed",
    },
}


# ==============================================================
# MAIN ROADMAP
# ==============================================================

def render_roadmap(
    profile,
    engine_output,
    safe_call,
):

    st.markdown(
        """
        <div class="pp-eyebrow">
            YOUR JOURNEY
        </div>

        <h2 class="pp-section-title">
            Learning Roadmap
        </h2>

        <p class="pp-section-description">
            A structured, prerequisite-aware path from
            where you are now to where you want to go.
        </p>
        """,
        unsafe_allow_html=True,
    )

    roadmap = (
        engine_output.get("roadmap")
        or []
    )

    # ==========================================================
    # EMPTY STATE
    # ==========================================================

    if not roadmap:

        st.markdown(
            """
            <div class="pp-card">

                <div style="
                    font-family:var(--font-display);
                    font-weight:700;
                    margin-bottom:0.4rem;
                ">
                    No roadmap generated yet
                </div>

                <div style="
                    color:var(--text-muted);
                    font-size:0.86rem;
                ">
                    Try adjusting your profile or career goal
                    and generate your learning path again.
                </div>

            </div>
            """,
            unsafe_allow_html=True,
        )

        return

    # ==========================================================
    # SESSION STATE
    # ==========================================================

    if (
        "roadmap_progress"
        not in st.session_state
    ):

        st.session_state.roadmap_progress = {}

    progress = (
        st.session_state.roadmap_progress
    )

    # ==========================================================
    # PROGRESS CALCULATION
    # ==========================================================

    total_steps = len(roadmap)

    completed_steps = 0
    in_progress_steps = 0

    for step in roadmap:

        if isinstance(step, dict):

            skill = step.get(
                "skill",
                "Unknown Skill",
            )

            status = progress.get(
                skill,
                "Not Started",
            )

            if status == "Completed":

                completed_steps += 1

            elif status == "In Progress":

                in_progress_steps += 1

    progress_percentage = (
        completed_steps / total_steps
        if total_steps > 0
        else 0
    )

    # ==========================================================
    # ROADMAP OVERVIEW
    # ==========================================================

    st.markdown(
        f"""
        <div class="pp-roadmap-overview">

            <div class="pp-roadmap-overview-top">

                <div>

                    <div class="pp-roadmap-overview-label">
                        LEARNING PROGRESS
                    </div>

                    <div class="pp-roadmap-overview-value">

                        {completed_steps} of {total_steps}

                        <span>
                            steps completed
                        </span>

                    </div>

                </div>

                <div class="pp-roadmap-percent">

                    {int(progress_percentage * 100)}%

                </div>

            </div>

            <div class="pp-roadmap-progress-track">

                <div
                    class="pp-roadmap-progress-fill"
                    style="
                        width:{progress_percentage * 100}%;
                    ">
                </div>

            </div>

        </div>
        """,
        unsafe_allow_html=True,
    )

    st.write("")

    # ==========================================================
    # ROADMAP TIMELINE
    # ==========================================================

    for index, step in enumerate(roadmap):

        is_last = (
            index == len(roadmap) - 1
        )

        render_roadmap_step(
            step_number=index + 1,
            step=step,
            is_last=is_last,
        )

    # ==========================================================
    # SUMMARY
    # ==========================================================

    st.write("")

    render_progress_summary(
        total_steps,
        in_progress_steps,
        completed_steps,
    )


# ==============================================================
# ROADMAP STEP
# ==============================================================

def render_roadmap_step(
    step_number,
    step,
    is_last=False,
):

    # ==========================================================
    # SAFE FALLBACK
    # ==========================================================

    if not isinstance(step, dict):

        st.markdown(
            f"""
            <div class="pp-roadmap-step-card">

                <div class="pp-roadmap-step-number">
                    STEP {step_number:02d}
                </div>

                <div class="pp-step-skill">
                    {html.escape(str(step))}
                </div>

            </div>
            """,
            unsafe_allow_html=True,
        )

        return

    # ==========================================================
    # EXTRACT DATA
    # ==========================================================

    skill = step.get(
        "skill",
        "Unknown Skill",
    )

    priority = step.get(
        "priority",
        "N/A",
    )

    difficulty = step.get(
        "difficulty",
        "N/A",
    )

    prerequisites = (
        step.get("prerequisites", [])
        or []
    )

    resources = (
        step.get("resources", [])
        or step.get(
            "recommended_resources",
            [],
        )
        or []
    )

    # ==========================================================
    # CURRENT STATUS
    # ==========================================================

    progress = (
        st.session_state.roadmap_progress
    )

    current_status = progress.get(
        skill,
        "Not Started",
    )

    status_data = STATUS_CONFIG.get(
        current_status,
        STATUS_CONFIG["Not Started"],
    )

    status_label = status_data["label"]

    status_class = status_data["class"]

    # ==========================================================
    # TIMELINE
    # ==========================================================

    rail_column, content_column = st.columns(
        [0.07, 0.93],
        gap="small",
    )

    with rail_column:

        line_html = ""

        if not is_last:

            line_html = """
            <div class="pp-roadmap-timeline-line">
            </div>
            """

        st.markdown(
            f"""
            <div class="pp-roadmap-timeline">

                <div class="
                    pp-roadmap-dot
                    {status_class}
                ">

                    {status_label}

                </div>

                {line_html}

            </div>
            """,
            unsafe_allow_html=True,
        )

    # ==========================================================
    # STEP CONTENT
    # ==========================================================

    with content_column:

        opacity = (
            "0.68"
            if current_status == "Not Started"
            else "1"
        )

        st.markdown(
            f"""
            <div
                class="pp-roadmap-step-card"
                style="opacity:{opacity};">

                <div class="pp-roadmap-step-header">

                    <div>

                        <div class="
                            pp-roadmap-step-number">

                            STEP {step_number:02d}

                        </div>

                        <div class="pp-step-skill">

                            {html.escape(str(skill))}

                        </div>

                    </div>

                    <div class="
                        pp-roadmap-status-badge
                        {status_class}
                    ">

                        {html.escape(str(current_status))}

                    </div>

                </div>

                <div class="pp-roadmap-meta">

                    <span>

                        Difficulty:
                        <b>
                            {html.escape(str(difficulty))}
                        </b>

                    </span>

                    <span class="
                        pp-roadmap-meta-divider
                    ">
                        •
                    </span>

                    <span>

                        Priority:
                        <b>
                            {html.escape(str(priority))}
                        </b>

                    </span>

                </div>

            </div>
            """,
            unsafe_allow_html=True,
        )

        # ======================================================
        # PREREQUISITES
        # ======================================================

        if prerequisites:

            prerequisites_text = ", ".join(
                str(item)
                for item in prerequisites
            )

        else:

            prerequisites_text = "None"

        st.markdown(
            f"""
            <div class="pp-roadmap-detail">

                <div class="pp-roadmap-detail-label">

                    PREREQUISITES

                </div>

                <div class="pp-roadmap-detail-text">

                    {html.escape(prerequisites_text)}

                </div>

            </div>
            """,
            unsafe_allow_html=True,
        )

        # ======================================================
        # RESOURCES
        # ======================================================

        if resources:

            resource_html = ""

            for resource in resources[:4]:

                if isinstance(
                    resource,
                    dict,
                ):

                    title = (
                        resource.get("title")
                        or resource.get("name")
                        or "Learning Resource"
                    )

                    url = (
                        resource.get("url")
                        or resource.get("link")
                    )

                    safe_title = html.escape(
                        str(title)
                    )

                    if url:

                        safe_url = html.escape(
                            str(url),
                            quote=True,
                        )

                        resource_html += f"""
                        <a
                            href="{safe_url}"
                            target="_blank"
                            class="pp-resource-chip">

                            {safe_title} ↗

                        </a>
                        """

                    else:

                        resource_html += f"""
                        <span class="pp-resource-chip">

                            {safe_title}

                        </span>
                        """

                else:

                    resource_html += f"""
                    <span class="pp-resource-chip">

                        {html.escape(str(resource))}

                    </span>
                    """

            st.markdown(
                f"""
                <div class="pp-roadmap-resources">

                    <div class="
                        pp-roadmap-detail-label
                    ">

                        RECOMMENDED RESOURCES

                    </div>

                    <div class="pp-resource-list">

                        {resource_html}

                    </div>

                </div>
                """,
                unsafe_allow_html=True,
            )

        # ======================================================
        # STATUS SELECTOR
        # ======================================================

        new_status = st.selectbox(
            "Progress Status",

            STATUS_OPTIONS,

            index=STATUS_OPTIONS.index(
                current_status
            ),

            key=(
                f"roadmap_status_"
                f"{step_number}_"
                f"{skill}"
            ),

            label_visibility="collapsed",
        )

        if new_status != current_status:

            st.session_state.roadmap_progress[
                skill
            ] = new_status

            st.rerun()

        st.write("")


# ==============================================================
# PROGRESS SUMMARY
# ==============================================================

def render_progress_summary(
    total_steps,
    in_progress_steps,
    completed_steps,
):

    st.markdown(
        """
        <div class="pp-eyebrow">

            PROGRESS SUMMARY

        </div>
        """,
        unsafe_allow_html=True,
    )

    col1, col2, col3 = st.columns(3)

    with col1:

        st.markdown(
            f"""
            <div class="pp-summary-card">

                <div class="pp-summary-value">

                    {total_steps}

                </div>

                <div class="pp-summary-label">

                    TOTAL STEPS

                </div>

            </div>
            """,
            unsafe_allow_html=True,
        )

    with col2:

        st.markdown(
            f"""
            <div class="pp-summary-card">

                <div class="pp-summary-value">

                    {in_progress_steps}

                </div>

                <div class="pp-summary-label">

                    IN PROGRESS

                </div>

            </div>
            """,
            unsafe_allow_html=True,
        )

    with col3:

        st.markdown(
            f"""
            <div class="pp-summary-card">

                <div class="pp-summary-value">

                    {completed_steps}

                </div>

                <div class="pp-summary-label">

                    COMPLETED

                </div>

            </div>
            """,
            unsafe_allow_html=True,
        )
