"""
PathPilot AI — Learning Roadmap UI

This file handles ONLY roadmap presentation and progress tracking.
It does not modify backend intelligence logic.
"""

import streamlit as st


# ==============================================================
# ROADMAP STATUS CONFIGURATION
# ==============================================================

STATUS_OPTIONS = [
    "Not Started",
    "In Progress",
    "Completed",
]

STATUS_CONFIG = {
    "Not Started": {
        "label": "○",
        "class": "roadmap-not-started",
    },
    "In Progress": {
        "label": "◐",
        "class": "roadmap-in-progress",
    },
    "Completed": {
        "label": "✓",
        "class": "roadmap-completed",
    },
}


# ==============================================================
# MAIN ROADMAP RENDERER
# ==============================================================

def render_roadmap(profile, engine_output, safe_call):
    """
    Render the learning roadmap generated by the IntelligenceEngine.

    Backend data is preserved exactly as provided through engine_output.
    """

    st.markdown(
        """
        <div class="pp-eyebrow">YOUR JOURNEY</div>
        <h2 class="pp-section-title">Learning Roadmap</h2>
        <p class="pp-section-description">
            Follow your prerequisite-aware learning path step by step.
        </p>
        """,
        unsafe_allow_html=True,
    )

    roadmap = engine_output.get("roadmap") or []

    # ----------------------------------------------------------
    # EMPTY STATE
    # ----------------------------------------------------------

    if not roadmap:
        st.markdown(
            """
            <div class="pp-card">
                <div style="font-weight:600; margin-bottom:6px;">
                    No roadmap available yet
                </div>
                <div style="color:var(--text-muted); font-size:0.88rem;">
                    Try adjusting your learning profile or career goal.
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )
        return

    # ----------------------------------------------------------
    # SESSION STATE
    # ----------------------------------------------------------

    if "roadmap_progress" not in st.session_state:
        st.session_state.roadmap_progress = {}

    progress = st.session_state.roadmap_progress

    # ----------------------------------------------------------
    # PROGRESS CALCULATION
    # ----------------------------------------------------------

    total_steps = len(roadmap)

    completed_steps = 0
    in_progress_steps = 0

    for step in roadmap:
        if isinstance(step, dict):
            skill = step.get("skill", "Unknown Skill")
            status = progress.get(skill, "Not Started")

            if status == "Completed":
                completed_steps += 1

            elif status == "In Progress":
                in_progress_steps += 1

    progress_percentage = (
        completed_steps / total_steps
        if total_steps > 0
        else 0
    )

    # ----------------------------------------------------------
    # ROADMAP OVERVIEW CARD
    # ----------------------------------------------------------

    st.markdown(
        f"""
        <div class="pp-roadmap-overview">
            <div class="pp-roadmap-overview-top">
                <div>
                    <div class="pp-roadmap-overview-label">
                        LEARNING PROGRESS
                    </div>

                    <div class="pp-roadmap-overview-value">
                        {completed_steps} of {total_steps}
                        <span>steps completed</span>
                    </div>
                </div>

                <div class="pp-roadmap-percent">
                    {int(progress_percentage * 100)}%
                </div>
            </div>

            <div class="pp-roadmap-progress-track">
                <div
                    class="pp-roadmap-progress-fill"
                    style="width:{progress_percentage * 100}%;">
                </div>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.write("")

    # ----------------------------------------------------------
    # ROADMAP TIMELINE
    # ----------------------------------------------------------

    for index, step in enumerate(roadmap):

        is_last = index == len(roadmap) - 1

        render_roadmap_step(
            step_number=index + 1,
            step=step,
            is_last=is_last,
        )

    # ----------------------------------------------------------
    # SUMMARY
    # ----------------------------------------------------------

    st.write("")

    render_progress_summary(
        total_steps,
        in_progress_steps,
        completed_steps,
    )


# ==============================================================
# INDIVIDUAL ROADMAP STEP
# ==============================================================

def render_roadmap_step(step_number, step, is_last=False):

    # ----------------------------------------------------------
    # SAFE FALLBACK FOR NON-DICT DATA
    # ----------------------------------------------------------

    if not isinstance(step, dict):

        st.markdown(
            f"""
            <div class="pp-roadmap-step-card">
                <div class="pp-roadmap-step-number">
                    STEP {step_number:02d}
                </div>

                <div class="pp-step-skill">
                    {step}
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )

        return

    # ----------------------------------------------------------
    # EXTRACT BACKEND DATA SAFELY
    # ----------------------------------------------------------

    skill = step.get("skill", "Unknown Skill")

    priority = step.get("priority", "N/A")

    difficulty = step.get("difficulty", "N/A")

    prerequisites = (
        step.get("prerequisites", [])
        or []
    )

    resources = (
        step.get("resources", [])
        or step.get("recommended_resources", [])
        or []
    )

    # ----------------------------------------------------------
    # CURRENT STATUS
    # ----------------------------------------------------------

    progress = st.session_state.roadmap_progress

    current_status = progress.get(
        skill,
        "Not Started",
    )

    status_data = STATUS_CONFIG.get(
        current_status,
        STATUS_CONFIG["Not Started"],
    )

    status_label = status_data["label"]
    status_class = status_data["class"]

    # ----------------------------------------------------------
    # TIMELINE LAYOUT
    # ----------------------------------------------------------

    rail_col, content_col = st.columns(
        [0.07, 0.93],
        gap="small",
    )

    # ----------------------------------------------------------
    # TIMELINE RAIL
    # ----------------------------------------------------------

    with rail_col:

        if is_last:

            line_html = ""

        else:

            line_html = """
            <div class="pp-roadmap-timeline-line"></div>
            """

        st.markdown(
            f"""
            <div class="pp-roadmap-timeline">
                <div class="pp-roadmap-dot {status_class}">
                    {status_label}
                </div>

                {line_html}
            </div>
            """,
            unsafe_allow_html=True,
        )

    # ----------------------------------------------------------
    # STEP CONTENT
    # ----------------------------------------------------------

    with content_col:

        step_opacity = (
            "0.68"
            if current_status == "Not Started"
            else "1"
        )

        st.markdown(
            f"""
            <div
                class="pp-roadmap-step-card"
                style="opacity:{step_opacity};"
            >

                <div class="pp-roadmap-step-header">

                    <div>
                        <div class="pp-roadmap-step-number">
                            STEP {step_number:02d}
                        </div>

                        <div class="pp-step-skill">
                            {skill}
                        </div>
                    </div>

                    <div class="pp-roadmap-status-badge {status_class}">
                        {current_status}
                    </div>

                </div>

                <div class="pp-roadmap-meta">

                    <span>
                        Difficulty:
                        <b>{difficulty}</b>
                    </span>

                    <span class="pp-roadmap-meta-divider">•</span>

                    <span>
                        Priority:
                        <b>{priority}</b>
                    </span>

                </div>

            </div>
            """,
            unsafe_allow_html=True,
        )

        # ------------------------------------------------------
        # PREREQUISITES
        # ------------------------------------------------------

        if prerequisites:

            prerequisites_text = ", ".join(
                str(item)
                for item in prerequisites
            )

        else:

            prerequisites_text = "None"

        st.markdown(
            f"""
            <div class="pp-roadmap-detail">

                <div class="pp-roadmap-detail-label">
                    PREREQUISITES
                </div>

                <div class="pp-roadmap-detail-text">
                    {prerequisites_text}
                </div>

            </div>
            """,
            unsafe_allow_html=True,
        )

        # ------------------------------------------------------
        # RESOURCES
        # ------------------------------------------------------

        if resources:

            resource_html = ""

            for resource in resources[:4]:

                if isinstance(resource, dict):

                    title = (
                        resource.get("title")
                        or resource.get("name")
                        or "Learning Resource"
                    )

                    url = (
                        resource.get("url")
                        or resource.get("link")
                    )

                    if url:

                        resource_html += f"""
                        <a
                            href="{url}"
                            target="_blank"
                            class="pp-resource-chip"
                        >
                            {title} ↗
                        </a>
                        """

                    else:

                        resource_html += f"""
                        <span class="pp-resource-chip">
                            {title}
                        </span>
                        """

                else:

                    resource_html += f"""
                    <span class="pp-resource-chip">
                        {resource}
                    </span>
                    """

            st.markdown(
                f"""
                <div class="pp-roadmap-resources">

                    <div class="pp-roadmap-detail-label">
                        RECOMMENDED RESOURCES
                    </div>

                    <div class="pp-resource-list">
                        {resource_html}
                    </div>

                </div>
                """,
                unsafe_allow_html=True,
            )

        # ------------------------------------------------------
        # STATUS CONTROL
        # ------------------------------------------------------

        new_status = st.selectbox(
            "Progress Status",
            STATUS_OPTIONS,
            index=STATUS_OPTIONS.index(current_status),
            key=f"roadmap_status_{step_number}_{skill}",
            label_visibility="collapsed",
        )

        if new_status != current_status:

            st.session_state.roadmap_progress[
                skill
            ] = new_status

            st.rerun()

        st.write("")


# ==============================================================
# PROGRESS SUMMARY
# ==============================================================

def render_progress_summary(
    total_steps,
    in_progress_steps,
    completed_steps,
):

    st.markdown(
        """
        <div class="pp-eyebrow">
            PROGRESS SUMMARY
        </div>
        """,
        unsafe_allow_html=True,
    )

    col1, col2, col3 = st.columns(3)

    with col1:

        st.markdown(
            f"""
            <div class="pp-summary-card">

                <div class="pp-summary-value">
                    {total_steps}
                </div>

                <div class="pp-summary-label">
                    TOTAL STEPS
                </div>

            </div>
            """,
            unsafe_allow_html=True,
        )

    with col2:

        st.markdown(
            f"""
            <div class="pp-summary-card">

                <div class="pp-summary-value">
                    {in_progress_steps}
                </div>

                <div class="pp-summary-label">
                    IN PROGRESS
                </div>

            </div>
            """,
            unsafe_allow_html=True,
        )

    with col3:

        st.markdown(
            f"""
            <div class="pp-summary-card">

                <div class="pp-summary-value">
                    {completed_steps}
                </div>

                <div class="pp-summary-label">
                    COMPLETED
                </div>

            </div>
            """,
            unsafe_allow_html=True,
        )
