"""
PathPilot AI — Learning roadmap rendering.
Displays the prerequisite-aware roadmap generated by IntelligenceEngine
as a vertical timeline, plus lightweight session-state progress tracking.
"""

import streamlit as st


STATUS_OPTIONS = ["Not Started", "In Progress", "Completed"]
DOT_CLASS = {"Not Started": "", "In Progress": "dot-inprogress", "Completed": "dot-completed"}
DOT_LABEL = {"Not Started": "○", "In Progress": "◐", "Completed": "✓"}


def render_roadmap(profile, engine_output, safe_call):
    st.markdown('<div class="pp-eyebrow">YOUR JOURNEY</div><h2 class="pp-section-title">Learning Roadmap</h2>', unsafe_allow_html=True)

    roadmap = engine_output.get("roadmap") or []

    if not roadmap:
        st.markdown(
            '<div class="pp-card">No roadmap has been generated yet. Try adjusting your profile or career goal.</div>',
            unsafe_allow_html=True,
        )
        return

    if "roadmap_progress" not in st.session_state:
        st.session_state.roadmap_progress = {}

    total = len(roadmap)
    progress = st.session_state.roadmap_progress
    completed = sum(1 for s in roadmap if isinstance(s, dict) and progress.get(s.get("skill"), "Not Started") == "Completed")

    st.markdown(
        f'<p style="color:var(--text-muted); font-size:0.87rem; margin-bottom:1.2rem;">'
        f'{completed} of {total} steps completed</p>',
        unsafe_allow_html=True,
    )
    st.progress(completed / total if total else 0)
    st.write("")

    for idx, step in enumerate(roadmap, start=1):
        _render_step(idx, step, is_last=(idx == total))

    st.write("")
    _render_progress_summary(roadmap)


def _render_step(idx, step, is_last):
    if not isinstance(step, dict):
        st.markdown(f'<div class="pp-card">Step {idx}: {step}</div>', unsafe_allow_html=True)
        return

    skill = step.get("skill", "Unknown Skill")
    priority = step.get("priority", "N/A")
    difficulty = step.get("difficulty", "N/A")
    prerequisites = step.get("prerequisites", []) or []
    resources = step.get("resources", []) or step.get("recommended_resources", []) or []

    progress = st.session_state.roadmap_progress
    current_status = progress.get(skill, "Not Started")
    dot_class = DOT_CLASS.get(current_status, "")
    dot_label = DOT_LABEL.get(current_status, "○")
    is_future = current_status == "Not Started"

    line_html = '<div class="pp-timeline-line"></div>' if not is_last else '<div style="width:2px; flex:1;"></div>'

    col_rail, col_body = st.columns([0.05, 0.95])
    with col_rail:
        st.markdown(
            f"""
            <div class="pp-timeline-rail">
                <div class="pp-timeline-dot {dot_class}">{dot_label}</div>
                {line_html}
            </div>
            """,
            unsafe_allow_html=True,
        )

    with col_body:
        opacity = "0.72" if is_future else "1"
        st.markdown(f'<div style="opacity:{opacity};">', unsafe_allow_html=True)
        st.markdown(f'<div style="font-family:var(--font-mono); color:var(--text-faint); font-size:0.77rem; margin-bottom:2px;">STEP {idx:02d}</div>', unsafe_allow_html=True)
        st.markdown(f'<div class="pp-step-skill">{skill}</div>', unsafe_allow_html=True)
        st.markdown(f'<div class="pp-step-meta">{difficulty} · Priority {priority}</div>', unsafe_allow_html=True)

        prereq_text = ", ".join(prerequisites) if prerequisites else "None"
        st.markdown(
            f'<p style="color:var(--text-muted); font-size:0.85rem; margin-bottom:0.4rem;">'
            f'<b style="color:var(--text-primary);">Prerequisites:</b> {prereq_text}</p>',
            unsafe_allow_html=True,
        )

        if resources:
            chips = ""
            for r in resources[:4]:
                if isinstance(r, dict):
                    title = r.get("title") or r.get("name") or "Resource"
                    url = r.get("url") or r.get("link")
                    chips += f'<a href="{url}" target="_blank" style="text-decoration:none;"><span class="pp-chip">{title}</span></a>' if url else f'<span class="pp-chip">{title}</span>'
                else:
                    chips += f'<span class="pp-chip">{r}</span>'
            st.markdown(chips, unsafe_allow_html=True)
        else:
            st.markdown('<p style="color:var(--text-faint); font-size:0.82rem;">No specific resources listed yet.</p>', unsafe_allow_html=True)
        st.markdown('</div>', unsafe_allow_html=True)

        new_status = st.selectbox(
            "Status",
            STATUS_OPTIONS,
            index=STATUS_OPTIONS.index(current_status),
            key=f"status_{skill}_{idx}",
            label_visibility="collapsed",
        )
        if new_status != current_status:
            st.session_state.roadmap_progress[skill] = new_status
            st.rerun()

        st.markdown('<div style="margin-bottom:0.6rem;"></div>', unsafe_allow_html=True)


def _render_progress_summary(roadmap):
    total = len(roadmap)
    progress = st.session_state.roadmap_progress

    completed = sum(1 for step in roadmap if isinstance(step, dict) and progress.get(step.get("skill"), "Not Started") == "Completed")
    in_progress = sum(1 for step in roadmap if isinstance(step, dict) and progress.get(step.get("skill"), "Not Started") == "In Progress")

    st.markdown('<div class="pp-card">', unsafe_allow_html=True)
    st.markdown('<div class="pp-eyebrow">PROGRESS SUMMARY</div>', unsafe_allow_html=True)
    col1, col2, col3 = st.columns(3)
    with col1:
        st.markdown(f'<div class="pp-metric-value" style="font-size:1.5rem;">{total}</div><div class="pp-metric-label">Total Steps</div>', unsafe_allow_html=True)
    with col2:
        st.markdown(f'<div class="pp-metric-value" style="font-size:1.5rem;">{in_progress}</div><div class="pp-metric-label">In Progress</div>', unsafe_allow_html=True)
    with col3:
        st.markdown(f'<div class="pp-metric-value" style="font-size:1.5rem;">{completed}</div><div class="pp-metric-label">Completed</div>', unsafe_allow_html=True)
    st.markdown('</div>', unsafe_allow_html=True)
